### ISSUE TITLE
Thread 'main' panicked at 'Invalid width (was 347, but range is 1-256)'

### ISSUE THREAD

**Issue by futuremotiondev** [Ortham/svg_to_ico#3]
Full console:
``C:\Tools\scripts>svg_to_ico.exe -i "C:\Tools\icons\00 To Create\svg\coding.svg" -o "C:\Tools\icons\00 To Create\svg\coding.ico"
thread 'main' panicked at 'Invalid width (was 347, but range is 1-256)', C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\ico-0.1.0\src\lib.rs:435:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.``

Here is a zip of the SVG file I want to convert:
[coding.zip](https://github.com/Ortham/svg_to_ico/files/7516717/coding.zip)

Running W10 Pro, 21H1 (OS Build 19043.1348)

**Comment by ehamawy** [comment]
having this issue too

**Comment by Ortham** [comment]
Should be fixed in 56c27fe41ab08dcfc76d678f59d14bf63ebdee2b.
